CatalogoClientes.Web/Models/Remessa.cs
using System.Collections.Generic;
using System.Web;

namespace CatalogoClientes.Web.Models
{
  public class Remessa
  {
    public IEnumerable<HttpPostedFileBase> Arquivos { get; set; }
  }
}

CatalogoClientes.Web/Controllers/ArquivoController.cs
using CatalogoClientes.Dominio.Entidades;
using System.Web.Mvc;

namespace CatalogoClientes.Web.Controllers
{
  public class ArquivoController : Controller
  {
    // GET: Arquivo
    public ActionResult ExibirImagem(int id)
    {
      using (NorthwindContexto db = new NorthwindContexto())
      {
        var arquivoRetorno = db.Clientes.Find(id);
        return File(arquivoRetorno.Imagem, arquivoRetorno.ImagemTipo);
      }
    }
  }
}

CatalogoClientes.Web/Controllers/CategoriaController.cs
using CatalogoClientes.Dominio.Entidades;
using CatalogoClientes.Dominio.Repositorio;
using System.Web.Mvc;

namespace CatalogoClientes.Web.Controllers
{
  public class CategoriaController : Controller
  {
    private NorthwindContexto db = new NorthwindContexto();
    private IRepositorio<Categoria> _repositorioCategoria;

    public CategoriaController()
    {
      _repositorioCategoria = new CategoriaRepositorio(new NorthwindContexto());
    }

    // GET: Categoria
    public ActionResult Categoria()
    {
      ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoryID", "CategoryName");
      //ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoryID", "CategoryName", "3");
      return View();
    }

    // POST: Categoria
    [HttpPost]
    public ActionResult Categoria(string CategoriaId)
    {
      string valor = CategoriaId;
      string valorRequest = Request["CategoriaId"];

      // Recarrega pra não dar erro
      ViewBag.CategoriaId = new SelectList(db.Categorias, "CategoryID", "CategoryName");
      return View();
    }
  }
}

CatalogoClientes.Web/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CatalogoClientes.Dominio.Entidades;
using CatalogoClientes.Dominio.Repositorio;
using PagedList;

namespace CatalogoClientes.Web.Controllers
{
  public class ClienteController : Controller
  {
    private NorthwindContexto db = new NorthwindContexto();
    private IRepositorio<Cliente> _repositorioCliente;

    // GET: Cliente
    public ClienteController()
    {
      _repositorioCliente = new ClienteRepositorio(new NorthwindContexto());
    }

    public ActionResult Catalogo(int? pagina)
    {
      int tamanhoPagina = 1;
      int numeroPagina = pagina ?? 1;
      return View(_repositorioCliente.GetTodos().ToPagedList(numeroPagina, tamanhoPagina));
    }

    //// GET: Cliente
    //public ActionResult Index()
    //{
    //  return View(db.Clientes.ToList());
    //}

    // GET: Cliente/Details/5
    public ActionResult Details(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Cliente cliente = db.Clientes.Find(id);
      if (cliente == null)
      {
        return HttpNotFound();
      }
      return View(cliente);
    }

    // GET: Cliente/Create
    public ActionResult Create()
    {
      return View();
    }

    // POST: Cliente/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create([Bind(Include = "ClienteId,Nome,Email,Endereco,Imagem,ImagemTipo")] Cliente cliente, HttpPostedFileBase uploadImg)
    {
      if (ModelState.IsValid)
      {
        if (uploadImg != null && uploadImg.ContentLength > 0)
        {
          var arqImagem = new Cliente
          {
            ImagemTipo = uploadImg.ContentType
          };
          using (var reader = new BinaryReader(uploadImg.InputStream))
          {
            arqImagem.Imagem = reader.ReadBytes(uploadImg.ContentLength);
          }
          cliente.Imagem = arqImagem.Imagem;
          cliente.ImagemTipo = arqImagem.ImagemTipo;
        }

        db.Clientes.Add(cliente);
        db.SaveChanges();
        TempData["mensagem"] = string.Format("{0} : foi incluído com sucesso", cliente.Nome);
        return RedirectToAction("Catalogo");
      }

      return View(cliente);

      //if (ModelState.IsValid)
      //{
      //  db.Clientes.Add(cliente);
      //  db.SaveChanges();
      //  return RedirectToAction("Catalogo");
      //}

      //return View(cliente);
    }

    // GET: Cliente/Edit/5
    public ActionResult Edit(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Cliente cliente = db.Clientes.Find(id);
      if (cliente == null)
      {
        return HttpNotFound();
      }
      return View(cliente);
    }

    // POST: Cliente/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Edit([Bind(Include = "ClienteId,Nome,Email,Endereco,Imagem,ImagemTipo")] Cliente cliente, HttpPostedFileBase uploadImg)
    {
      if (ModelState.IsValid)
      {
        if (uploadImg != null && uploadImg.ContentLength > 0)
        {
          var arqImagem = new Cliente
          {
            ImagemTipo = uploadImg.ContentType
          };
          using (var reader = new BinaryReader(uploadImg.InputStream))
          {
            arqImagem.Imagem = reader.ReadBytes(uploadImg.ContentLength);
          }
          cliente.Imagem = arqImagem.Imagem;
          cliente.ImagemTipo = arqImagem.ImagemTipo;
        }

        db.Entry(cliente).State = EntityState.Modified;
        db.SaveChanges();
        TempData["mensagem"] = string.Format("{0} : foi atualizado com sucesso", cliente.Nome);
        return RedirectToAction("Catalogo");
      }

      return View(cliente);

      //if (ModelState.IsValid)
      //{
      //  db.Entry(cliente).State = EntityState.Modified;
      //  db.SaveChanges();
      //  return RedirectToAction("Catalogo");
      //}
      //return View(cliente);
    }

    // GET: Cliente/Delete/5
    public ActionResult Delete(int? id)
    {
      if (id == null)
      {
        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
      }
      Cliente cliente = db.Clientes.Find(id);
      if (cliente == null)
      {
        return HttpNotFound();
      }
      return View(cliente);
    }

    // POST: Cliente/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public ActionResult DeleteConfirmed(int id)
    {
      Cliente cliente = db.Clientes.Find(id);
      db.Clientes.Remove(cliente);
      db.SaveChanges();
      TempData["mensagem"] = string.Format("{0} : foi excludo com sucesso", cliente.Nome);
      return RedirectToAction("Catalogo");
    }

    protected override void Dispose(bool disposing)
    {
      if (disposing)
      {
        db.Dispose();
      }
      base.Dispose(disposing);
    }
  }
}

CatalogoClientes.Web/Controllers/UploadMultiplosController.cs
using CatalogoClientes.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CatalogoClientes.Web.Controllers
{
  /// <summary>
  /// No web.config, em <system.web><httpRuntime>:
  /// - maxRequestLength: default 4096 kb. Request máximo.
  /// - requestLengthDiskThreshold: default 80 kb.  Buffer de memória máximo.
  /// - executionTimeout: default 110 segundos. Tempo de execução máximo.
  /// </summary>
  public class UploadMultiplosController : Controller
  {
    // GET: Remessa
    public ActionResult Index()
    {
      return View();
    }

    // GET: Remessa
    [HttpPost]
    public ActionResult Index(Remessa arq)
    {
      try
      {
        string nomeArquivo = "";
        string arquivosEnviados = "";
        foreach (var arquivo in arq.Arquivos)
        {
          if (arquivo.ContentLength > 0)
          {
            nomeArquivo = Path.GetFileName(arquivo.FileName);
            var caminho = Path.Combine(Server.MapPath("~/Imagens/Uploaded"), nomeArquivo);
            arquivo.SaveAs(caminho);
          }

          arquivosEnviados += ", " + nomeArquivo;
        }
        ViewBag.Mensagem = "Arquivo(s): " + arquivosEnviados + ", enviado(s) com sucesso.";
      }
      catch (Exception ex)
      {
        ViewBag.Mensagem = "Erro: " + ex.Message;
      }

      return View();
    }
  }
}

CatalogoClientes.Web/Views/Categoria/Categoria.cshtml
@{
  ViewBag.Title = "Categoria";
}

<h2>Ano</h2>
<select name="ano">
  @for (int i = 0; i <= 5; i++)
  {
    <option>@(DateTime.Now.AddYears(i).Year)</option>
  }
</select>

<h2>Dias da Semana:</h2>
@Html.DropDownList("Dia da Semana", new List<SelectListItem>
{
  new SelectListItem{ Text = "Domingo", Value = "1"},
  new SelectListItem{ Text = "Segunda-Feira", Value = "2"},
  new SelectListItem{ Text = "Terça-Feira", Value = "3"},
  new SelectListItem{ Text = "Quarta-Feira", Value = "4"},
  new SelectListItem{ Text = "Quinta-Feira", Value = "5"},
  new SelectListItem{ Text = "Sexta-Feira", Value = "6", Selected = true},
  new SelectListItem{ Text = "Sábado", Value = "7"}
}, "Selecione o dia da semana")


<h2>Categorias:</h2>
@using (Html.BeginForm())
{
  @Html.DropDownList("CategoriaId", "Selecione uma Categoria")
  <input type="submit" value="Enviar" />
}

CatalogoClientes.Web/Views/Cliente/Catalogo.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<CatalogoClientes.Dominio.Entidades.Cliente>

@{
    ViewBag.Title = "Catalogo de Clientes";
}

@foreach (var item in Model)
{
    @Html.Partial("_CatalogoResumo", item);
}

<p class="text-primary">
  Página @Model.PageNumber de @Model.PageCount
</p>

<span class="btn-group pull-right">
  @Html.PagedListPager(Model, pagina => Url.Action("Catalogo", new { pagina }))
</span>

CatalogoClientes.Web/Views/Cliente/Create.cshtml
@model CatalogoClientes.Dominio.Entidades.Cliente

@{
  ViewBag.Title = "Create";
}

<div class="clientes panel panel-primary">
  <div class="panel-heading panel-head">Cadastro de Clientes</div>
  <div class="panel-body">
    @using (Html.BeginForm("Create", "Cliente", null, FormMethod.Post, new
    {
      enctype = "multipart/form-data" // Necessário por causa do fileUpload.
    }))
    {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
      <hr />
      @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.Label("Imagem", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          <input type="file" id="Imagem" name="uploadImg" />
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <input type="submit" value="Criar Cliente" class="btn btn-success" />
        </div>
      </div>
    </div>

    <div>
      @Html.ActionLink("Retornar", "Catalogo")
    </div>
    }
  </div>
</div>

CatalogoClientes.Web/Views/Cliente/Delete.cshtml
@model CatalogoClientes.Dominio.Entidades.Cliente

@{
  ViewBag.Title = "Delete";
}

<div class="clientes panel panel-primary">
  <div class="panel-heading panel-head">Cadastro de Clientes</div>
  <div class="panel-body">
    <h3>Deseja deletar esse registro?</h3>
    <div>
      <h4>Cliente</h4>
      <hr />
      <dl class="dl-horizontal">
        @if (Model.Imagem != null)
        {
          <dt>
            Imagem
          </dt>
          <dd>
            <img class="img-thumbnail" src="@Url.Action("ExibirImagem", "Arquivo", new { id=Model.ClienteId })" />
          </dd>
        }
        else
        {
          <dt>
            Imagem
          </dt>
          <dd>
            <img class="thumbnail" src="~/Imagens/no-photo-available-md.png" width="150" height="150" />
          </dd>
        }

        <dt>
          @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
          @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
          @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
          @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
          @Html.DisplayNameFor(model => model.Endereco)
        </dt>

        <dd>
          @Html.DisplayFor(model => model.Endereco)
        </dd>

      </dl>

      @using (Html.BeginForm())
      {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
          <input type="submit" value="Delete" class="btn btn-default" /> |
          @Html.ActionLink("Retornar", "Catalogo")
        </div>
      }
    </div>
  </div>
</div>

CatalogoClientes.Web/Views/Cliente/Details.cshtml
@model CatalogoClientes.Dominio.Entidades.Cliente

@{
  ViewBag.Title = "Details";
}

<div class="clientes panel panel-primary">
  <div class="panel-heading panel-head">Cadastro de Clientes</div>
  <div class="panel-body">
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
      @if (Model.Imagem != null)
      {
        <dt>
          Imagem
        </dt>
        <dd>
          <img class="img-thumbnail" src="@Url.Action("ExibirImagem", "Arquivo", new { id=Model.ClienteId })" />
        </dd>
      }
      else
      {
        <dt>
          Imagem
        </dt>
        <dd>
          <img class="thumbnail" src="~/Imagens/no-photo-available-md.png" width="150" height="150" />
        </dd>
      }

      <dt>
        @Html.DisplayNameFor(model => model.Nome)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.Nome)
      </dd>

      <dt>
        @Html.DisplayNameFor(model => model.Email)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.Email)
      </dd>

      <dt>
        @Html.DisplayNameFor(model => model.Endereco)
      </dt>

      <dd>
        @Html.DisplayFor(model => model.Endereco)
      </dd>

    </dl>
  </div>
  <p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ClienteId }, new { @class = "btn btn-success" }) |
    @Html.ActionLink("Retornar", "Catalogo")
  </p>
</div>

CatalogoClientes.Web/Views/Cliente/Edit.cshtml
@model CatalogoClientes.Dominio.Entidades.Cliente

@{
  ViewBag.Title = "Editar Clientes";
}

<div class="clientes panel panel-primary">
  <div class="panel-heading panel-head">Cadastro de Clientes</div>
  <div class="panel-body">
    @using (Html.BeginForm("Edit", "Cliente", null, FormMethod.Post, new
    {
      enctype = "multipart/form-data" // Necessário por causa do fileUpload.
    }))
    {
      @Html.AntiForgeryToken()

    <div class="form-horizontal">
      <h4>Cliente</h4>
      <hr />
      @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      @Html.HiddenFor(model => model.ClienteId)

      <div class="form-group">
        @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
      </div>

      <div class="form-group">
        @Html.LabelFor(model => model.Endereco, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          @Html.EditorFor(model => model.Endereco, new { htmlAttributes = new { @class = "form-control" } })
          @Html.ValidationMessageFor(model => model.Endereco, "", new { @class = "text-danger" })
        </div>
      </div>

      @if (Model.Imagem != null)
      {
        <div class="form-group">
          <span class="control-label col-md-2">
            Imagem Atual
          </span>
          <div class="col-md-10">
            <img class="img-thumbnail" src="@Url.Action("ExibirImagem", "Arquivo", new { id = Model.ClienteId })" />
          </div>
        </div>
      }
      else
      {
        <div class="form-group">
          <span class="control-label col-md-2">
            Imagem Atual
          </span>
          <div class="col-md-10">
            <img class="thumbnail" src="~/Imagens/no-photo-available-md.png" width="150" height="150" />
          </div>
        </div>
      }

      <div class="form-group">
        @Html.Label("Nova Imagem", new { @class = "control-label col-md-2" })
        <div class="col-md-10">
          <input type="file" id="Imagem" name="uploadImg" />
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <input type="submit" value="Salvar Alterações" class="btn btn-success" />
        </div>
      </div>
    </div>
    }

    <div>
      @Html.ActionLink("Retornar", "Catalogo", null, new { @class = "btn btn-primary" })
    </div>
  </div>
</div>

CatalogoClientes.Web/Views/Shared/_CatalogoResumo.cshtml
@model CatalogoClientes.Dominio.Entidades.Cliente

<div class="clientes panel panel-primary">
  <div class="panel-heading panel-head">Cadastro de Clientes</div>
  <div class="panel-body">
    <a id="CriarCliente" href="@Url.Action("Create")" class="btn btn-success">
      <span class="glyphicon glyphicon-plus">Incluir Cliente</span>
    </a>
    <table>
      <tr>
        <td rowspan="3">
          @if (Model.Imagem != null)
          {
            <div class="pull-left" style="margin-right: 10px;">
              <img class="img-thumbnail" src="@Url.Action("ExibirImagem", "Arquivo", new { id=Model.ClienteId })" />
            </div>
          }
          else
          {
            <div class="pull-left" style="margin-right: 10px;">
              <img class="thumbnail" src="~/Imagens/no-photo-available-md.png" width="150" height="150" />
            </div>
          }
        </td>
        <td>
          <a class="btn btn-primary btn-lg">
            <strong>@Model.Nome</strong>
          </a>
        </td>
      </tr>
      <tr>
        <td>
          @Model.Email
          <br />
          @Model.Endereco
        </td>
      </tr>
      <tr>
        <td>
          <div class="btn-group">
            @Html.ActionLink("Editar", "Edit", new { id = Model.ClienteId }, new { @class = "btn btn-success" })
            @Html.ActionLink("Detalhes", "Details", new { id = Model.ClienteId }, new { @class = "btn btn-primary" })
            @Html.ActionLink("Deletar", "Delete", new { id = Model.ClienteId }, new { @class = "btn btn-danger" })
          </div>
        </td>
      </tr>
    </table>
  </div>
</div>

CatalogoClientes.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="container">
        <div class="navbar navbar-inverse">
          <img src="~/Imagens/LogoMacorattiNet.gif" />
        </div>
        <div class="row panel">
            <div id="menu" class="col-xs-3">
                Menu
            </div>
            <div class="col-xs-8">
                @if (TempData["mensagem"] != null)
                {
                    <div class="alert alert-success">@TempData["mensagem"]</div>
                }
                @RenderBody()
            </div>
        </div>
    </div>

</body>
</html>

CatalogoClientes.Web/Views/UploadMultiplos/Index.cshtml
@model CatalogoClientes.Web.Models.Remessa

@{
    ViewBag.Title = "Index";
}

<h2>Upload de Arquivos</h2>
@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
  <div class="well">
    <table class="table table-striped">
      <tr>
        <td>Arquivo: </td>
        <td><input type="file" id="Arquivos" name="Arquivos" multiple /></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td><input type="submit" name="submit" value="Enviar Arquivo" /></td>
      </tr>
      <tr>
        <td>@ViewBag.Mensagem</td>
      </tr>
    </table>
  </div>
}